### PR TITLE
Fixed missing rows bug

### PR DESCRIPTION
**Pull request by mannycolon**
## Describe what your pull request addresses

- [ ]

## Test Instructions

- [ ] Open https://deploy-preview-75--tn-converter-app.netlify.app/
- [ ] Search for Owner: `manny_colon` and slug: `es-419_tq`
- [ ] Before selecting the repo please click on the following icon to open the repo
Screen-Shot-2021-03-23-at-12 29 23-PM
- [ ] Now click to open the repo
- [ ] Select `1JN`
- [ ] Verify one by one that all items in the markdown files are represented on the right-hand columns (Target TSV Translation Notes (es-419_1jn))
- [ ] Feel free to follow instructions in https://app.zenhub.com/workspaces/uw-apps-5f5bb97cdac78f0020a50f5e/issues/unfoldingword-box3/tn-converter-app/17#issuecomment-813676758

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-box3/tn-converter-app/75)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@mannycolon I ended up with one extra Spanish question.  Is this expected? 
Screen Shot 2021-04-08 at 9 02 14 AM

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-box3/tn-converter-app/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Comment by mannycolon** [comment]
No it's not exoected. That's strange, I tested the same project and never got an extra target row

**Comment by PhotoNomad0** [comment]
@mannycolon I left it open and checked back again.  This time I have two extra Spanish questions!  Wonder if it is related to scrolling?  Or maybe sometimes when realigning, that an English question gets dropped?

**Comment by PhotoNomad0** [comment]
Here is the tsv: 
[tq_1JN.tsv.zip](https://github.com/unfoldingWord-box3/tn-converter-app/files/6279143/tq_1JN.tsv.zip)

**Comment by PhotoNomad0** [comment]
Also: 
Screen Shot 2021-04-08 at 10 16 12 AM

**Comment by PhotoNomad0** [comment]
PS - excuse any mistaken alignments - I have forgotten a lot of my Spanish vocabulary.

**Comment by mannycolon** [comment]
> Also:
> Screen Shot 2021-04-08 at 10 16 12 AM

It looks like you rearrange the columns, Is this the case? or was this like that the first time the project was generated?

**Comment by mannycolon** [comment]
> PS - excuse any mistaken alignments - I have forgotten a lot of my Spanish vocabulary.

No worries, you actually did a very good job

**Comment by PhotoNomad0** [comment]
> > Also:
> > Screen Shot 2021-04-08 at 10 16 12 AM
> 
> It looks like you rearrange the columns, Is this the case? or was this like that the first time the project was generated?

This was the first time I generated this project.  But it did seem a couple of times when I dragged a line, I missed the intended spot and it got dropped in an empty line above.  It seemed like the alignments immediately below got shifted.  I probably should have done a video recording.  I might have some time later to retry in a different browser.

**Pull request merged**
